[package]
name = "SimpleMapTest"
version = "0.0.0"
upgrade_policy = "compatible"

[addresses]
msafe = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }